- name: Setup testkay bastion hosts
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup variable
      include_vars: vars/vpc_setup

    - name: Import VPC setup variable
      include_vars: vars/output_vars

    - name: Create testkay bastion ec2 key
      ec2_key:
        name: bastion-key
        region: "{{region}}"
      register: key_out

    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed
    
    - name: Create security group for bastion host
      ec2_group:
        name: bastion-host-sg
        description: allow port 22 from everywhere and all ports within the security group
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{anywhere_ip}}"
      register: bastionSG_out

    - name: Create Bastion host
      ec2:
        key_name: testkay-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host"
          Project: testkay
          Owner: Devops Team
        exact_count: 1
        count_tag:
          Name: "Bastion_host"
          Project: testkay
          Owner: Devops Team
        group_id: "{{bastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out
