- name: Setup testkay stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup variable
      include_vars: vars/vpc_output_vars

    - name: Import testkay setup variable
      include_vars: vars/testkay_stack_setup

    - name: Create testkay ec2 key
      ec2_key:
        name: testkay-stack-key
        region: "{{region}}"
      register: testkaykey_out

    - name: Save private key into file loginkey_testkay.pem
      copy:
        content: "{{testkaykey_out.key.private_key}}"
        dest: "./loginkey_testkay.pem"
        mode: 0600
      when: testkaykey_out.changed
    
    - name: Create security group for load balancer
      ec2_group:
        name: testkayELB-sg
        description: allow port 80 from everywhere and all ports within the security group
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: "{{anywhere_ip}}"
      register: testkayELBSG_out

    - name: Create security group for testkay stack
      ec2_group:
        name: testkayStack-sg
        description: allow port 22 from everywhere and all ports within the security group
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{testkayELBSG_out.group_id}}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{BastionSGid}}"
      register: testkayStackSG_out
