- name: Setup testkay stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup variable
      include_vars: vars/vpc_output_vars

    - name: Import testkay setup variable
      include_vars: vars/testkay_stack_setup

    - name: Create testkay ec2 key
      ec2_key:
        name: testkay-stack-key
        region: "{{region}}"
      register: testkaykey_out

    - name: Save private key into file loginkey_testkay.pem
      copy:
        content: "{{testkaykey_out.key.private_key}}"
        dest: "./loginkey_testkay.pem"
        mode: 0600
      when: testkaykey_out.changed
    
    - name: Create security group for load balancer
      ec2_group:
        name: testkayELB-sg
        description: allow port 80 from everywhere and all ports within the security group
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: "{{anywhere_ip}}"
      register: testkayELBSG_out

    - name: Create security group for testkay stack
      ec2_group:
        name: testkayStack-sg
        description: allow port 22 from everywhere and all ports within the security group
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{testkayELBSG_out.group_id}}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{BastionSGid}}"
      register: testkayStackSG_out

    - name: Update security group for testkay stack with it's own security group id
      ec2_group:
        name: testkayStack-sg
        description: allow port 22 from everywhere and all ports within the security group
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{testkayStackSG_out.group_id}}"

    - name: Create Nginx web01
      ec2:
        key_name: testkay-stack-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{nginx_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "web01"
          Project: testkay
          Owner: Devops Team
        exact_count: 1
        count_tag:
          Name: "web01"
          Project: testkay
          Owner: Devops Team
        group_id: "{{testkayStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: web01_out

    - name: Create Tomcat app01
      ec2:
        key_name: testkay-stack-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{tomcat_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "app01"
          Project: testkay
          Owner: Devops Team
        exact_count: 1
        count_tag:
          Name: "app01"
          Project: testkay
          Owner: Devops Team
        group_id: "{{testkayStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: app01_out

    - name: Create Memcache mc01
      ec2:
        key_name: testkay-stack-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{memcache_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "mc01"
          Project: testkay
          Owner: Devops Team
        exact_count: 1
        count_tag:
          Name: "mc01"
          Project: testkay
          Owner: Devops Team
        group_id: "{{testkayStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: mc01_out

    - name: Create RabbitMQ mq01
      ec2:
        key_name: testkay-stack-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{rmq_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "mq01"
          Project: testkay
          Owner: Devops Team
        exact_count: 1
        count_tag:
          Name: "mq01"
          Project: testkay
          Owner: Devops Team
        group_id: "{{testkayStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: mq01_out

    - name: Create MySql db01
      ec2:
        key_name: testkay-stack-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{mysql_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: db01
          Project: testkay
          Owner: Devops Team
        exact_count: 1
        count_tag:
          Name: "db01"
          Project: testkay
          Owner: Devops Team
        group_id: "{{testkayStackSG_out.group_id}}"
        vpc_subnet_id: "{{privsub1id}}"
      register: db01_out

    - debug:
        var: db01_out
